apiVersion: v1
kind: Secret
metadata:
  name: password-manager-api-secrets
  namespace: default
  labels:
    app: password-manager-api
type: Opaque
data:
  # DB_PASSWORD: ejemplo "MiPassword123!" codificado en base64
  DB_PASSWORD: TWlQYXNzd29yZDEyMyE=
  # JWT_SECRET: ejemplo "mi-super-secreto-jwt-key-2024" codificado en base64
  JWT_SECRET: bWktc3VwZXItc2VjcmV0by1qd3Qta2V5LTIwMjQ=

